export const ProxyTypes = {
  APPROVAL_CATALOG: 'APPROVAL_CATALOG',
  ORACLE_ROUTER: 'ORACLE_ROUTER',
  COLLATERAL_FUND: 'COLLATERAL_FUND',
  YIELD_DISTRIBUTOR: 'YIELD_DISTRIBUTOR',
  PREMIUM_FUND: 'PREMIUM_FUND',
  IMPERPETUAL_INDEX_POOL: 'IMPERPETUAL_INDEX_POOL',
  INSURED_POOL: 'INSURED_POOL',
} as const;
