name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Tests
        run: npm run test

      - name: Build package
        run: npm run build:package

      - name: Publish
        run: |
          echo "$(PACKAGE_JSON_VERSION=grep '"version":' package.json | cut -d\" -f4)" >> $GITHUB_ENV
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name ${{ github.actor }}
          npm version --force ${{ env.PACKAGE_JSON_VERSION }}-${{ github.sha }}
          npm publish
