name: Run checks

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Lint
        run: npm run eslint

      - name: Types
        run: npm run tsc

      - name: Tests
        run: npm run test

  slither:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Slither)
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Compile
        run: npm run compile

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run Slither
        run: slither . --config-file .slither.json