name: Publish package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Setup publisher
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm config set commit-hooks false
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      
      - name: Bump the application version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Compile
        run: npm run compile

      - name: Build package
        run: npm run build:package

      - name: Publish package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version update
        run: git push --no-verify
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
