name: Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build package
        run: npm run build:package

      - name: Publish
        run: |
          npm config set access public
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm publish
